name: Swift

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger Swift
        uses: docker://ghcr.io/danger/danger-swift:3.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
